### PR TITLE
[3439][ADD] stock_picking_accounting_date

### PR DESCRIPTION
**Pull request by rinaldifirdaus**
[3439](https://www.quartile.co/web?db=quartile&token=dMRr78CMkEX6gyy9nTiv#id=3439&action=771&model=project.task&view_type=form&menu_id=505)

### CODE REVIEW

**Comment by rinaldifirdaus** [comment]
@AungKoKoLin1997 Thanks lin for your support. i added commit to adjust accounting date field to before scheduled date.

**Review by yostashiro — APPROVED** [review]
I have added a commit to improve the field visibility.  Also added translation.

@AungKoKoLin1997 Shall we create a PR in OCA? Description should be updated with more background info / reasoning.

**Comment by AungKoKoLin1997** [comment]
> Shall we create a PR in OCA? Description should be updated with more background info / reasoning.

Yes. I think so. But I still don't have fully understanding of background and there is no explanation in task. I will ask aldi and arrange.

**Comment by yostashiro** [comment]
@rinaldifirdaus Can you please move this to axls-oca?

**Comment by rinaldifirdaus** [comment]
Superseded by axls-oca [#56](https://github.com/qrtl/axls-oca/pull/56)

**Pull request closed without merging**
