### PR TITLE
[16.0][4045][MIG] mail_hide_send_message: Migration to 16.0

### PR DESCRIPTION
**Pull request by AungKoKoLin1997**
[4045](https://www.quartile.co/web#id=4045&cids=3&model=project.task&view_type=form)

### CODE REVIEW

**Comment by yostashiro** [comment]
@liuhehe1995 Please do a functional test and report back.

**Review by liuhehe1995 — COMMENTED** [review]
I performed a functional test in my Development Env; it worked as expected.
please refer to the screenshot for details. 
Before adding this module, chatter has 3 options, which are "Send message", "Log note" and "Activities". 
After adding this module, the "Send message" option in the chatter is hidden, leaving only the remaining 2 options.
BEFORE
AFTER

**Review by yostashiro — APPROVED** [review]
Code review.

**Review by rinaldifirdaus — APPROVED** [review]
Functional test: LGTM

**Comment by rinaldifirdaus** [comment]
@yostashiro , can we have this PR merged? thank you

**Pull request merged**
